# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build fofa_viewer release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-package: jdk+fx
          java-version: '1.8'
          distribution: 'adopt'
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build fofa_viewer
        run: mvn -DskipTests assembly:assembly -f pom.xml

      - name: Copy out packages fofa_viewer
        run: |
          cp target/fofaviewer-jar-with-dependencies.jar .
          mv fofaviewer-jar-with-dependencies.jar fofaviewer.jar
          mv config-example.properties config.properties
          zip fofaviewer.zip fofaviewer.jar config.properties

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{steps.github_release.outputs.changelog}}
          draft: false
          prerelease: false
      - name: Upload fofa_viewer
        id: upload-release-fofa_viewer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: fofaviewer.zip
          asset_name: fofaviewer_${{ steps.get_version.outputs.VERSION }}_.zip
          asset_content_type: application/gzip